### ISSUE TITLE
Looker - what does it integrate?

### ISSUE THREAD

**Issue by darrenhaken** [GoogleCloudPlatform/datacatalog-connectors-bi#1]
If you run the Looker connector what data does it integrate into the Catalog?

**Comment by mesmacosta** [comment]
Hi Daren,
You can expect the connector to ingest: Folder, Dashboard, Dashboard Element (aka Tile), and Query elements to Data Catalog.

Recently a medium article was published with more details about this integration, you can check it out at:
https://medium.com/google-cloud/google-cloud-data-catalog-and-looker-integration-4ebefdef6a34

**Comment by mesmacosta** [comment]
Closing this, if you need more details please reopen. 

Thanks
