### ISSUE TITLE
[FEATURE] Fields metadata to be included in Qlik Connector

### ISSUE THREAD

**Issue by anugrah86** [GoogleCloudPlatform/datacatalog-connectors-bi#108]
Currently the Qlik connector scrapes only for Dimensions, Measures, Sheets and Visualizations using the Engine JSON API. 

However, many of the visualisations also use "Fields", which is not captured in the connector.

https://help.qlik.com/en-US/sense/November2021/Subsystems/Hub/Content/Sense_Hub/Visualizations/data-in-your-visualization.htm

This field list can be retrieved by using "qType": "FieldList" similar to how "qType": "DimensionList"  is used for Dimensions. 

Thank you!

**Comment by ricardolsmendes** [comment]
Hi, @anugrah86, thanks for filling this feature request.
We need more details to evaluate the feasibility of such a feature, ok?

As you noticed, the Qlik Sense Connector currently scrapes metadata from Master Items (Dimensions, Measures, Visualizations) and Sheets through the Engine JSON API. 
1. For Master Items, we perform the API calls in the following order: `OpenDoc` > `GetAllInfos` > `<GET-ITEM>` > `GetProperties`, replacing `<GET-ITEM>` with `GetDimension`, `GetMeasure`, and `GetObject` respectly.
   
   We filter `GetAllInfos`'s response to:
   1.1. find all elements that have `"qType": "dimension"` and then make the subsequent `GetDimension` calls;
   1.2. find all elements that have `"qType": "measure"` and then make the subsequent `GetMeasure` calls;
   1.3. find all elements that have `"qType": "masterobject"` and then make the subsequent `GetObject` calls.

1. For Sheets, we call `OpenDoc` > `GetObjects`, passing the below params:
    ```python
    'params': {
        'qOptions': {
            'qTypes': ['sheet'],
        },
    },
    ```

This means we don't use API calls with `"qType": "DimensionList"` so far.
That said, could you provide more details on how `"qType": "FieldList"` could be used to scrape Fields' metadata?

Thanks,
