### ISSUE TITLE
[BUG] Looker connector throws "Requires authentication" error when scraping metadata takes too long

### ISSUE THREAD

**Issue by ricardolsmendes** [GoogleCloudPlatform/datacatalog-connectors-bi#32]
**What happened**:
I'm using the `google-datacatalog-looker-connector` to ingest metadata from a large Looker instance into Google Data Catalog. This Looker instance has hundreds of queries, and scraping their metadata takes too long (I believe more than 1h). After scraping metadata for such a long time, the connector fails with the message:
```
looker_sdk.error.SDKError: {"message":"Requires authentication.","documentation_url":"http://docs.looker.com/"}
```

**What you expected to happen**:
I expect the connector to ingest metadata no matter how large the source Looker instance is.

**How to reproduce it (as minimally and precisely as possible)**:
Run any set of scrape operations that take very long to complete, actually more than 1h.

**Anything else we need to know?**:
I didn't investigate how Looker's SDK manages the REST API credentials, but this error might be related to a token expiration. Refreshing the token from time to time during the scrape stage might fix it.

**Comment by pmurias** [comment]
Hi, we are aware of the issue, and plan to fix it in the future after a new connector is done.
