### ISSUE TITLE
ADD support for Python3.6 on looker2datacatalog

### ISSUE THREAD

**Issue by mesmacosta** [GoogleCloudPlatform/datacatalog-connectors-bi#5]
**What would you like to be added**:
Make the looker2datacatalog connector work with Python3.6

**Why is this needed**:
Currently tableau2datacatalog works with both Python3.6 and Python3.7, since looker does not work with Python3.6 the CI is executing only for Python3.7. 
With this change we can enable our CI to run on both versions and increase our version coverage.

**Comment by ricardolsmendes** [comment]
Hi @mesmacosta,
this is not feasible since [looker-sdk](https://pypi.org/project/looker-sdk/) requires Python >=3.7.0, <3.9.

Closing this. Please reopen if you have further questions. Thanks!
