### ISSUE TITLE
[FEATURE] Create a BI connector for Sisense

### ISSUE THREAD

**Issue by davidhayter-karhoo** [GoogleCloudPlatform/datacatalog-connectors-bi#70]
**What would you like to be added**:
It would be great to add support for a datacatalog-connectors-bi for Sisense.

**Why is this needed**:
[Sisense](https://www.sisense.com/) is a popular BI solution, named as a visionary in the Gartner [quadrant](https://www.sisense.com/en-gb/gartner-magic-quadrant/) :-)
It has a rich REST API: https://sisense.dev/reference/rest/v1.html
It would allow us and the Sisense community to use GCP datacatalog as our metadata management solution.

Let me know if I can help in anyway

Many thanks
David

**Comment by ricardolsmendes** [comment]
Hi @davidhayter-karhoo, thanks for filing this feature request! I will be happy to work on it :).
Would you be available to discuss an MVP?

**Comment by davidhayter-karhoo** [comment]
Hi @ricardolsmendes,  sure, here's a proposal for initial Sisense [entities](https://documentation.sisense.com/latest/getting-started/concepts.htm#gsc.tab=0) to map to Data Catalog in the MVP.

- Folder - Dashboards can be organized into folders and subfolders to aid navigation

- Dashboard - A dashboard is a collection of one or more widgets that visualize the data that you select and design

- Widget - Each widget is a dynamic visualization of data. You pick the type of data to appear in a widget and you pick the type of visualization (chart type)

- Field - Widgets and filters are composed of fields that represent the data in your data sources. Each field represents a column of data in an ElastiCube (dataset) table

- JAQL - Sisense dashboards, widgets and filters use JAQL to query Sisense Elasticubes (datamodels) tables and fields

**Sisense References**
- Our current Sisense Windows Version: 8.2.5.11026 v1
- [REST API v1](https://sisense.dev/reference/rest/v1.html) 
- [Using Sisense JAQL](https://sisense.dev/guides/query/jaql/)
- [Sisense JAQL syntax](https://sisense.dev/reference/jaql/)
- [Using JAQL queries via REST API](https://support.sisense.com/hc/en-us/articles/115002802107-Extracting-Retrieving-Results-from-Widgets-to-JSON-Format-using-JAQL-Queries-)
- [Sisense support site](https://support.sisense.com/hc/en-us)

Thanks

**Comment by ricardolsmendes** [comment]
Thanks, @davidhayter-karhoo! I'm finishing a couple of ongoing tasks and will take this one soon!

**Comment by ricardolsmendes** [comment]
I broke the MVP into smaller tasks that will help us to track progress and collaborate: https://github.com/GoogleCloudPlatform/datacatalog-connectors-bi/projects/1.

**Comment by ricardolsmendes** [comment]
The first version of the Sisense Connector was released and is available on PyPI: https://pypi.org/project/google-datacatalog-sisense-connector/0.1.0.
